import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Nav from '../components/Header/Nav'
import MentorCard from '../components/screen/MentorList/MentorCard'

export default function Home({ data }) {
  // const { data, error } = useSWR(
  //   getUrl(params, query),
  //   fetcher
  //   // , {initialData: events}
  // )

  // if (error) return <div>Failed to load</div>
  // if (!data) return <div>Loading...</div>
  // if (data.status == 'error')
  //   return (
  //     <>
  //       <div>{data.message}</div>
  //     </>
  //   )
  // useEffect(() => {
  //   // const face1 = faces.generate(null, { race: 'white', fatness: 7 })
  //   // const face2 = faces.generate(null, { race: 'white', fatness: 7 })
  //   // faces.display('my-div-id', face1, { race: 'black' })
  //   // faces.display('my-div-id2', face2, { race: 'black' })
  //   //
  // }, [])
  return (
    <>
      <Head>
        <title>Timesharing</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {Array.isArray(data) ? (
        <div className="flex flex-wrap -mx-3">
          {data.map((mentor, i) => (
            <MentorCard key={i} mentor={mentor} />
          ))}
        </div>
      ) : (
        <div className="flex flex-wrap -mx-3">
          {/* <MentorCard key={i} mentor={mentor} /> */}
        </div>
      )}
    </>
  )
}

export async function getServerSideProps() {
  const res = await fetch(`http://127.0.0.1:3000/api/mentor`)
  const { data } = await res.json()
  return { props: { data } }
}
